name: iris-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - joblib
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - seaborn
  - streamlit
  - ipykernel
